# Generated by Django 2.2.7 on 2019-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('search', models.CharField(default='', max_length=100)),
                ('symptoms', models.CharField(default='', max_length=1000)),
                ('precautions', models.CharField(default='', max_length=1500)),
                ('doctors', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
