# Generated by Django 2.2.7 on 2019-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
