# Generated by Django 2.2.7 on 2019-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_disease_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='content',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='search',
        ),
        migrations.AlterField(
            model_name='disease',
            name='doctors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='disease',
            name='precautions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default=''),
        ),
    ]
